In [23]:
import numpy as np

# Define the padded input matrices (R, G, B channels)
R_padded = np.array([
    [0, 0, 0, 0, 0, 0, 0, 0],
    [0, 112, 125, 25, 80, 220, 110, 0],
    [0, 150, 95, 15, 100, 115, 152, 0],
    [0, 200, 100, 48, 90, 70, 175, 0],
    [0, 187, 56, 43, 86, 180, 200, 0],
    [0, 190, 87, 70, 37, 24, 35, 0],
    [0, 80, 75, 65, 45, 32, 20, 0],
    [0, 0, 0, 0, 0, 0, 0, 0]
])

G_padded = np.array([
    [0, 0, 0, 0, 0, 0, 0, 0],
    [0, 150, 125, 38, 80, 20, 10, 0],
    [0, 130, 95, 25, 100, 115, 152, 0],
    [0, 80, 100, 148, 91, 70, 175, 0],
    [0, 170, 160, 43, 160, 170, 180, 0],
    [0, 100, 150, 70, 37, 124, 135, 0],
    [0, 85, 75, 65, 45, 232, 120, 0],
    [0, 0, 0, 0, 0, 0, 0, 0]
])

B_padded = np.array([
    [0, 0, 0, 0, 0, 0, 0, 0],
    [0, 200, 125, 25, 80, 220, 150, 0],
    [0, 50, 95, 15, 150, 115, 152, 0],
    [0, 90, 110, 48, 190, 70, 175, 0],
    [0, 180, 135, 43, 106, 180, 110, 0],
    [0, 55, 98, 70, 37, 24, 35, 0],
    [0, 78, 150, 65, 45, 32, 80, 0],
    [0, 0, 0, 0, 0, 0, 0, 0]
])

# Define filters
filter_R = np.array([
    [1, 1, 1, 0],
    [0, 1, 1, 1],
    [-1, 0, 0, 1],
    [-1, 0, 1, -1]
])

filter_G = np.array([
    [0, -1, -1, 0],
    [1, -1, 1, -1],
    [1, 0, 0, 1],
    [1, 0, 1, 1]
])

filter_B = np.array([
    [1, 1, 1, 0],
    [-1, 1, 1, 1],
    [0, 1, 0, 1],
    [-1, -1, 1, 1]
])

# Function to perform convolution
def conv2d(matrix, kernel, stride=1):
    output_size = ((matrix.shape[0] - kernel.shape[0]) // stride) + 1
    output = np.zeros((output_size, output_size))
    
    for i in range(output_size):
        for j in range(output_size):
            region = matrix[i:i+kernel.shape[0], j:j+kernel.shape[1]]
            output[i, j] = np.sum(region * kernel)
    
    return output

# Apply convolution
conv_R = conv2d(R_padded, filter_R)
conv_G = conv2d(G_padded, filter_G)
conv_B = conv2d(B_padded, filter_B)

# Sum the three convolved outputs
conv_output = conv_R + conv_G + conv_B

# Apply ReLU activation
relu_output = np.maximum(conv_output, 0)

# Display the convolution output after ReLU
print("Convolution Output after ReLU (5x5):")
print(relu_output.astype(int))  # Convert to integer for clarity

# Function to perform max pooling
def max_pooling(matrix, kernel_size=2, stride=2):
    output_size = (matrix.shape[0] - kernel_size) // stride + 1
    output = np.zeros((output_size, output_size))

    for i in range(0, output_size * stride, stride):
        for j in range(0, output_size * stride, stride):
            output[i//stride, j//stride] = np.max(matrix[i:i+kernel_size, j:j+kernel_size])
    
    return output

# Apply max pooling on ReLU output with stride=2
max_pooled_output = max_pooling(relu_output, kernel_size=2, stride=2)

# Display the final output after max pooling
print("\nFinal Output after Max Pooling (3x3):")
print(max_pooled_output.astype(int))  # Convert to integer for clarity


Convolution Output after ReLU (5x5):
[[1022  783 1315 1666 1071]
 [1195 1167 1518 2493 1700]
 [1292 1307 1531 1765 1411]
 [1463  666 1414 1655 1426]
 [1051 1058  784  717  673]]

Final Output after Max Pooling (3x3):
[[1195 2493]
 [1463 1765]]
